apiVersion: v1
kind: Service
metadata:
  name: naming-server-service
spec:
  selector:
    app: naming-server
  ports:
    - protocol: TCP
      port: 8761          # Porta pela qual o serviço será exposto dentro do cluster
      targetPort: 8761     # Porta no contêiner onde o naming-server está ouvindo
  type: ClusterIP          # Exposição interna do serviço dentro do cluster
