apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 80          # Porta exposta para o tráfego externo
      targetPort: 8765  # Porta interna do contêiner
  type: LoadBalancer    # Usa LoadBalancer para expor o serviço externamente
